version: 2

docker_defaults: &docker_defaults
  docker:
    - image: circleci/node:16.14.0-browsers
  working_directory: ~/project/repo

attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/project

install_steps: &install_steps
  steps:
    - checkout
    - restore_cache:
        name: Restore node_modules cache
        keys:
          - dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
          - dependency-cache-{{ .Branch }}-
          - dependency-cache-
    - run:
        name: Installing Dependencies
        command: |
          npm install --silent
    - save_cache:
        name: Save node_modules cache
        key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
          - node_modules/
    - persist_to_workspace:
        root: ~/project
        paths:
          - repo

workflows:
  version: 2
  build_pipeline:
    jobs:
      - build
      - create_artifact:
          requires:
            - build
      # - deploy:
      #     requires:
      #       - create_artifact
      #     filters:
      #       branches:
      #         only:
      #           - master

jobs:
  build:
    <<: *docker_defaults
    <<: *install_steps
  create_artifact:
    <<: *docker_defaults
    steps:
      - *attach_workspace
      - run:
          name: Creating public folder
          command: |
            sudo npm run build
  # deploy:
  #   <<: *docker_defaults
  #   steps:
  #     - *attach_workspace
  #     - run:
  #         name: Deploying GH Pages
  #         command: |
  #           sudo npm run deploy
